### ISSUE TITLE
Mouse pointer gets stuck

### ISSUE THREAD

**Issue by vmsh0** [aligrudi/fbvnc#2]
Every once in a while (can't identify the exact conditions) the mouse pointer gets stuck in a limited area. For example, it becomes impossible to move it to the left of some invisible line. To get it unstuck, it is sufficient to first move it all to the right.

I observed this while connecting to QEMU's integrated VNC server, with a Windows 2000 guest.

**Comment by aligrudi** [comment]
Riccardo Paolo Bestetti ***@***.***> wrote:
> Every once in a while (can't identify the exact conditions) the
> mouse pointer gets stuck in a limited area. For example, it becomes
> impossible to move it to the left of some invisible line. To get it
> unstuck, it is sufficient to first move it all to the right.

The main issue is the mouse driver:
  https://unix.stackexchange.com/questions/555082

> I observed this while connecting to QEMU's integrated VNC server,
> with a Windows 2000 guest.

I am not sure this version of Windows supports usb-tablet.

I tried before to fix this on the Fbvnc side.  I do not remember the
details now; it was not successful.

	Ali

**Comment by vmsh0** [comment]
I confirm this was the issue. Windows 2000 supports USB tablets and, as such, we managed to fix the issue. Thank you for your help!
